# .github/workflows/ci.yml
name: Run RSpec Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker containers
        run: docker-compose -f docker-compose.yml build

      - name: Run database setup
        run: docker-compose run --rm -e RAILS_ENV=test web bin/rails db:create db:migrate

      - name: Run RSpec tests
        run: docker-compose run --rm -e RAILS_ENV=test web bundle exec rspec

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}