name: Test Coverage

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" --health-timeout=5s --health-start-period=10s --health-interval=10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Set up PostgreSQL
        run: |
          sudo apt-get install -y postgresql-client
          psql -h localhost -U postgres -d app_test -c 'SELECT 1'

      - name: Install dependencies
        run: |
          bundle install
          yarn install

      - name: Run database migrations
        run: docker-compose run web bin/rails db:create db:migrate

      - name: Run tests with SimpleCov
        run: docker-compose run web bundle exec rspec

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
